apiVersion: v2
name: mychart
description: My awesome Helm chart
version: 0.1.0
dependencies:
- name: assets
  version: 0.1.0
  repository: "file://assets/charts"
- name: carts
  version: 0.1.0
  repository: "file://carts/charts"
- name: catalog
  version: 0.1.0
  repository: "file://catalog/charts"
- name: checkout
  version: 0.1.0
  repository: "file://checkout/charts"
- name: orders
  version: 0.1.0
  repository: "file://orders/charts"
- name: other
  version: 0.1.0
  repository: "file://other/charts"
- name: rabbitmq
  version: 0.1.0
  repository: "file://rabbitmq/charts"
- name: ui
  version: 0.1.0
  repository: "file://ui/charts"
