apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.db.name }}
  labels:
    app.kubernetes.io/created-by: eks-workshop
spec:
  type: {{ .Values.service.db.type }}
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.service.db.targetPort }}
      protocol: TCP
      name: {{ .Values.service.db.portName }}
  selector:
    app.kubernetes.io/name: carts 
    app.kubernetes.io/instance: carts
    app.kubernetes.io/component: dynamodb
