configMap:
  metadata:
    name: assets
  data:
    PORT: 8080

namespace:
  metadata: 
    name: assets

deployment:
  metadata:
    name: assets
  spec:
    replicas: 1
  resources:
    cpu: 250m
    memory: 512Mi

service:
  metadata:
    name: assets
    instance: assets
  service:
    port: 80
