apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app.kubernetes.io/created-by: eks-workshop
spec:
  type: {{ .Values.service.type }} #ClusterIP
  ports:
    - port: {{ .Values.service.Port }} #80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/component: service
