apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appInstance }}
    app.kubernetes.io/component: mysql
