apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-chart.fullname" . }}-catalog
data:
  DB_NAME: {{ .Values.db.name }}
  DB_ENDPOINT: {{ .Values.db.endpoint }}
  DB_READ_ENDPOINT: {{ .Values.db.readEndpoint }}
