configMap:
  metadata:
    name: orders
  data:
    springProfilesActive: mysql,rabbitmq
    springRabbitmqHost: rabbitmq.rabbitmq.svc

namespace:
  metadata:
    name: orders

service:
  name: orders-mysql
  port: 3306
  targetPort: mysql
  portName: mysql


deployment-mysql:
  spec:
    replicas: 1
  image:
    repository: public.ecr.aws/docker/library/mysql
    tag: 5.7
    pullPolicy: IfNotPresent

  mysqlRootPassword: my-secret-pw
  mysqlDatabase: orders
  mysqlUser: orders_user
  mysqlPassword: default_password

  containerPort: 3306
